modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "fungus_stew"
version = "${version}"
displayName = "Fungus Stew"
authors = "ENC_Euphony"
description = '''
Fungus stew made by nether fungus
'''
#logoFile = ""

[[dependencies.fungus_stew]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fungus_stew]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.fungus_stew]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "fungus_stew.mixins.json"
